-- MySQL Script generated by MySQL Workbench
-- Thu Nov 10 21:57:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema edziennik
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `edziennik` ;

-- -----------------------------------------------------
-- Schema edziennik
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `edziennik` DEFAULT CHARACTER SET latin1 ;
USE `edziennik` ;

-- -----------------------------------------------------
-- Table `edziennik`.`_prisma_migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edziennik`.`_prisma_migrations` ;

CREATE TABLE IF NOT EXISTS `edziennik`.`_prisma_migrations` (
  `id` VARCHAR(36) NOT NULL,
  `checksum` VARCHAR(64) NOT NULL,
  `finished_at` DATETIME(3) NULL DEFAULT NULL,
  `migration_name` VARCHAR(255) NOT NULL,
  `logs` TEXT NULL DEFAULT NULL,
  `rolled_back_at` DATETIME(3) NULL DEFAULT NULL,
  `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `applied_steps_count` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `edziennik`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edziennik`.`group` ;

CREATE TABLE IF NOT EXISTS `edziennik`.`group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `edziennik`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edziennik`.`user` ;

CREATE TABLE IF NOT EXISTS `edziennik`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(191) NOT NULL,
  `last_name` VARCHAR(191) NOT NULL,
  `address` VARCHAR(191) NOT NULL,
  `city` VARCHAR(191) NOT NULL,
  `group_id` INT(11) NOT NULL,
  `avatar` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `isTeacher` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `User_group_id_fkey` (`group_id` ASC) VISIBLE,
  CONSTRAINT `User_group_id_fkey`
    FOREIGN KEY (`group_id`)
    REFERENCES `edziennik`.`group` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `edziennik`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edziennik`.`subject` ;

CREATE TABLE IF NOT EXISTS `edziennik`.`subject` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `teacher_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Subject_teacher_id_fkey` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `Subject_teacher_id_fkey`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `edziennik`.`user` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `edziennik`.`grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edziennik`.`grade` ;

CREATE TABLE IF NOT EXISTS `edziennik`.`grade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `grade` INT(11) NOT NULL,
  `student_id` INT(11) NOT NULL,
  `subject_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Grade_student_id_fkey` (`student_id` ASC) VISIBLE,
  INDEX `Grade_subject_id_fkey` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `Grade_student_id_fkey`
    FOREIGN KEY (`student_id`)
    REFERENCES `edziennik`.`user` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `Grade_subject_id_fkey`
    FOREIGN KEY (`subject_id`)
    REFERENCES `edziennik`.`subject` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `edziennik`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edziennik`.`message` ;

CREATE TABLE IF NOT EXISTS `edziennik`.`message` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(191) NOT NULL,
  `sender_id` INT(11) NOT NULL,
  `receiver_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Message_sender_id_fkey` (`sender_id` ASC) VISIBLE,
  INDEX `Message_receiver_id_fkey` (`receiver_id` ASC) VISIBLE,
  CONSTRAINT `Message_receiver_id_fkey`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `edziennik`.`user` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `Message_sender_id_fkey`
    FOREIGN KEY (`sender_id`)
    REFERENCES `edziennik`.`user` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `edziennik`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `edziennik`.`schedule` ;

CREATE TABLE IF NOT EXISTS `edziennik`.`schedule` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `day` INT(11) NOT NULL,
  `time` INT(11) NOT NULL,
  `subject_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Schedule_subject_id_fkey` (`subject_id` ASC) VISIBLE,
  INDEX `Schedule_group_id_fkey` (`group_id` ASC) VISIBLE,
  CONSTRAINT `Schedule_group_id_fkey`
    FOREIGN KEY (`group_id`)
    REFERENCES `edziennik`.`group` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `Schedule_subject_id_fkey`
    FOREIGN KEY (`subject_id`)
    REFERENCES `edziennik`.`subject` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
